id = "c3-ex"
name = "c3-ex"
version = "0.0.4"
schema_version = 1
authors = ["DONG <dongrunyu2023@outlook.com>"]
description = "This extension bring basic c3 language support to zed. NOTE: This extension is still a WIP!"
repository = "https://github.com/handsomelittledong/c3-zed"

[language_servers.c3]
name = "c3"
language = "C3"

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
rev = "3bcb189c85a15d5e47a12947fbb25cd6604025f5"